version: '3.8'
services:
    mailhog:
        container_name: ${PROJECT_NAME}_mailhog
        image: 'mailhog/mailhog:latest'
        ports:
            - '8025:8025'

    redis:
        container_name: ${PROJECT_NAME}_redis
        image: 'redis:alpine'

    database:
        container_name: ${PROJECT_NAME}_database
        image: 'postgres:11.1-alpine'
        working_dir: /srv
        volumes:
            - '.:/srv'
        environment:
            - POSTGRES_USER=${APP_DATABASE_USER}
            - POSTGRES_PASSWORD=${APP_DATABASE_SECRET}
            - POSTGRES_DB=${APP_DATABASE_NAME}
        ports:
            - '5432:5432'

    elasticsearch:
        container_name: ${PROJECT_NAME}_elasticsearch
        image: 'elasticsearch:8.6.0'

    nginx:
        container_name: ${PROJECT_NAME}_nginx
        image: 'nginx:alpine'
        working_dir: /srv
        volumes:
            - '.:/srv'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        depends_on:
            -   php

    php:
        container_name: ${PROJECT_NAME}_php
        build: docker/php-fpm
        working_dir: /srv
        volumes:
            - '.:/srv'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        depends_on:
            - database
        env_file: .env
        extra_hosts:
            - host.docker.internal:host-gateway